version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: jobtracker-mysql

    environment:
      MYSQL_ROOT_PASSWORD: 7388@Devy
      MYSQL_DATABASE: job_tracker_db


    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p7388@Devy"]
        interval: 10s
        timeout: 5s
        retries: 10

  app:
    build: .
    container_name: jobtracker-api

    depends_on:
      mysql:
        condition: service_healthy


    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/job_tracker_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 7388@Devy
      SPRING_PROFILES_ACTIVE: docker

volumes:
  mysql_data: